---
channel: stable
addons:
  loki:
    repository: mdegat01/addon-loki
    target: loki
    image: ghcr.io/mdegat01/loki/{arch}
  promtail:
    repository: mdegat01/addon-promtail
    target: promtail
    image: ghcr.io/mdegat01/promtail/{arch}
  hedgedoc:
    repository: mdegat01/addon-hedgedoc
    target: hedgedoc
    image: ghcr.io/mdegat01/hedgedoc/{arch}
  sharry:
    repository: mdegat01/addon-sharry
    target: sharry
    image: ghcr.io/mdegat01/sharry/{arch}
  amr2mqtt:
    repository: mdegat01/addon-amr2mqtt
    target: amr2mqtt
    image: ghcr.io/mdegat01/amr2mqtt/{arch}
